#!/bin/bash  
# --------------------------------------------------------------------------- #
#                                                                             #
# nwps_val.cron : Script manages the running of the NWPS validation script    #
#             ${workdir}/nwps_webgraph.sh                                     #
#                                                                             #
# Remarks   - Can be run interactively, or from LL.                           #
#                                                                             #
# Last Changed : 10-26-2015                                     October 2015  #
# --------------------------------------------------------------------------- #
#PBS -N nwps_webpr
#PBS -j oe
#PBS -S /bin/bash
#PBS -q dev_transfer
#PBS -A NWPS-DEV
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=1
#PBS -l debug=true
#PBS -V
#PBS -o /lfs/h2/emc/ptmp/omd.wave/com/nwps/v1.5.0/nwps_webpr.o
#PBS -e /lfs/h2/emc/ptmp/omd.wave/com/nwps/v1.5.0/nwps_webpr.o

#mpirun.lsf cfp ${HOMEcron}/wfo_cmdfile
${HOMEcron}/nwps_webgraph_pr_dev.sh > ${HOMEcron}/nwps_web_pr.log 2>&1
